---
- name: Download information about latest versions
  apt:
    update-cache: yes
    cache_valid_time: 3600

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Remove unneeded packages
  become: yes
  # command: apt-get -y autoremove
  # force_apt_get: yes
  apt:
    autoremove: yes

- name: Clean apt cache
  apt:
    autoclean: yes
