---
alsa_out_card: 0
alsa_out_device: 0
alsa_setup: false
disable_nmi_watch: true
enable_sleep_suspend: true
i2c_load_dev: false
i2c_user_add: false
intel_hda_options: []
logind_configure: false
logind_idle_action: suspend
logind_idle_time: 600 # seconds
logind_lid_action: suspend
logind_powerbutton_action: poweroff
systemd_units_disable: []
systemd_units_enable: []
systemd_units_masked: []
vm_writeback: 1500
