---
- name: Install nginx web-server
  import_tasks: ngx_install.yml
  become: True
  tags:
    - ngx_install

- name: Configure nginx web-server
  import_tasks: ngx_configure.yml
  become: True
  tags:
    - ngx_install

- name: Provision HTTPs certificates
  import_tasks: ngx_https.yml
  become: True
  tags:
    - ngx_https
