---
- name: Install dependencies
  apt:
    name: '{{ pkg }}'
    state: latest
  vars:
    pkg:
      - nginx-light
      - python3-virtualenv
      - uvicorn

- name: Stop nginx
  systemd:
    name: nginx.service
    enabled: True
    masked: False
    state: stopped

- name: Clone EteSync repository
  git:
    repo: 'https://github.com/etesync/server'
    dest: '{{ esc_path }}'
    version: '{{ esc_version }}'

- name: Pip-install requirements into virtualenv
  pip: 
    requirements: '{{ esc_path }}/requirements.txt'
    virtualenv: '{{ esc_path }}/.venv'
