---
- name: Install EteSync server
  import_tasks: install.yml
  become: True
  tags:
    - esc_install

- name: Configure EteSync server
  import_tasks: configure_server.yml
  become: True
  tags:
    - esc_configure_server

- name: Configure nginx
  import_tasks: configure_nginx.yml
  become: True
  tags:
    - esc_configure_nginx

- name: Configure EteSync system user
  import_tasks: configure_user.yml
  become: True
  tags:
    - esc_configure_user

- name: Configure Uvicorn
  import_tasks: configure_uvicorn.yml
  become: True
  tags:
    - esc_configure_uvicorn

- name: Show details of the added EteBase superuser
  debug:
    msg: |
      Admin username: {{ esc_admin_out }}
      Make sure to login into {{ ansible_host }} and run:
      cd {{ esc_path }} && source ./venv/bin/activate \
      && ./manage.py changepassword {{ esc_admin }}
  when: esc_admins_num | int == 0

- name: EteBase superuser is already present
  debug:
    msg: >
      'EteBase has had superuser prior to this playbook run.
      Investigate manually if needed'
  when: esc_admins_num | int > 0
