---
- name: Install EteSync server
  import_tasks: install.yml
  become: True
  tags:
    - esc_install

- name: Configure EteSync server
  import_tasks: configure_server.yml
  become: True
  tags:
    - esc_configure_server

- name: Configure nginx
  import_tasks: configure_nginx.yml
  become: True
  tags:
    - esc_configure_nginx

- name: Configure EteSync user
  import_tasks: configure_user.yml
  become: True
  tags:
    - esc_configure_user

- name: Configure Uvicorn
  import_tasks: configure_uvicorn.yml
  become: True
  tags:
    - esc_configure_uvicorn
