---
- name: Install EteSync server
  import_tasks: install.yml
  become: True
  tags:
    - esc_install
- name: Configure EteSync server
  import_tasks: configure_server.yml
  become: True
  tags:
    - esc_configure_server
