---
- name: Re-read systemd settings
  systemd:
    daemon_reload: True
  listen: 'reread systemd'

- name: Reload systemd
  systemd:
    daemon_reexec: True
  listen: 'reload systemd'

- name: Reload ufw
  command: ufw reload
  listen: 'reload ufw'

- name: Reload sysctl
  shell: sysctl --system
  listen: 'reload sysctl'
