---
- name: Install requested software packages
  import_tasks: software_install.yml
  become: yes
  tags:
    - software_install

- name: Configure libvirt / KVM
  import_tasks: libvirt.yml
  become: yes
  when: virtio_install
  tags:
    - software_libvirt

- name: Configure services
  import_tasks: services.yml
  become: yes
  tags:
    - software_services

- name: Run all relevant handlers
  meta: flush_handlers
