---
- name: Disable and stop systemd units
  systemd:
    name: '{{ item }}'
    state: stopped
    enabled: no
  with_items: '{{ systemd_units_disable }}'
  when: systemd_units_disable | length > 0

- name: Enable systemd units
  systemd:
    name: '{{ item }}'
    enabled: yes
  with_items: '{{ systemd_units_enable }}'
  when: systemd_units_enable | length > 0
