---
- name: Install utilities
  apt:
    pkg:
      - archivemount
      - atool
      - bc
      - catdoc
      - checksec
      - colortest-python
      - docx2txt
      - entr
      - fzf
      - gcolor3
      - gnupg2
      - hexyl
      - jq
      - keepassxc
      - libsixel-bin
      - libxml2-utils # xmllint
      - light
      - odt2txt
      - pandoc
      - pmount
      - rlwrap # cht.sh dependency
      - scdaemon
      - taskwarrior
      - undertime
      - unicode-data
      - wordnet
      - wordnet-sense-index
      - yubioath-desktop
  when: setup_utils

- name: Launch KeepassXC via .desktop with 1.5x scale
  lineinfile:
    path: /usr/share/applications/org.keepassxc.KeePassXC.desktop
    regexp: '^Exec=keepassx.*'
    line: Exec=env QT_SCALE_FACTOR=1.5 keepassxc %f
  when: setup_utils

- name: Install Wayland desktop
  apt:
    pkg:
      - adwaita-icon-theme
      - adwaita-qt
      - gnome-icon-theme
      - gnome-themes-standard
      - libglib2.0-bin # gsettings
      - mako-notifier
      - qtwayland5
      - slurp # screen area selector
      - sway
      - swaybg
      - swayidle
      - swaylock
      - waybar
      - wdisplays
      - wf-recorder
      - wl-clipboard
      - wofi
  when: setup_wayland

- name: Install fonts
  apt:
    pkg:
      - fonts-jetbrains-mono
      - fonts-liberation
      - fonts-powerline
      - fonts-recommended
      - fonts-terminus
      - fonts-terminus-otb
  when: setup_fonts

- name: Install fuse/filesystems support
  apt:
    pkg:
      - dosfstools
      - exfatprogs
      - fuse-zip
      - gocryptfs
      - fuseiso
  when: setup_fs

- name: Install development tools
  apt:
    pkg:
      - bpython
      - cargo
      - git
      - make
      - python3-pip
      - python3-virtualenv
      - rustc
      - strace
  when: setup_dev

- name: Install office tools
  apt:
    pkg:
      - dbus-x11 # needed by loffice apparently
      - dictionaries-common
      - hunspell
      - hunspell-en-au
      - liblibreofficekitgtk # needed for menus
      - libreoffice-gtk3
      - libreoffice-l10n-en-gb
      - libreoffice-style-sifr
      - lyx
      - mythes-en-au
  when: setup_office

- name: Install internet tools
  apt:
    pkg:
      - aria2
      - filezilla
      - firefox-esr
      - firefox-esr-l10n-en-gb
      - nmap
      - socat
      - syncthing
      - syncthing-gtk
      - weechat
      - wget
      - whois
      - youtube-dl
  when: setup_internet

- name: Install multimedia packages
  apt:
    pkg:
      - ffmpeg
      - imv
      - libimage-exiftool-perl
      - mpd
      - mpv
      - ncmpcpp
  when: setup_multimedia

- name: Create mpd lyrics folder
  file:
    path: "{{ ansible_env.HOME }}/.cache/mpd/lyrics/"
    state: directory
    recurse: yes
  become: no
  when: setup_multimedia
  tags:
    - wtf
