---
# TODO: kernel.nmi_watchdog=0

- name: Residual packages
  apt:
    name: "{{ pkg }}"
  vars:
    pkg:
      - archivemount
      - aria2
      - atool
      - bc
      - bpython
      - cargo
      - catdoc
      - colortest-python
      - dictionaries-common
      - docx2txt
      - dosfstools
      - entr
      - exfatprogs
      - ffmpeg
      - filezilla
      - firefox-esr
      - firefox-esr-l10n-en-gb
      - fonts-croscore
      - fonts-liberation
      - fonts-powerline
      - fonts-recommended
      - fonts-terminus
      - fonts-terminus-otb
      - fuse-zip
      - fuseiso
      - fzf
      - gcolor3
      - git
      - gnome-icon-theme
      - gocryptfs
      - hexyl
      - hunspell
      - hunspell-en-au
      - imv
      - iwd
      - jq
      - keepassxc
      - libglib2.0-bin # gsettings
      - libimage-exiftool-perl
      - libreoffice-l10n-en-gb
      - libreoffice-style-sifr
      - libsixel-bin
      - libvirt-daemon-config-network
      - libvirt-daemon-config-nwfilter
      - libvirt-daemon-system
      - libxml2-util
      - light
      - lyx
      - mako-notifier
      - mpd
      - mpv
      - myspell-en-au
      - mythes-en-au
      - nmap
      - odt2txt
      - pandoc
      - pmount
      - powertop
      - python3-pip
      - python3-psutil
      - python3-virtualenv
      - qt5ct
      - qtwayland5
      - rlwrap # cht.sh dependency
      - rustc
      - scdaemon
      - slurp # screen area selector
      - socat
      - strace
      - sway
      - swaybg
      - swayidle
      - swaylock
      - syncthing
      - syncthing-gtk
      - taskwarrior
      - undertime
      - unicode-data
      - virt-manager
      - vit
      - wavemon
      - waybar
      - wdisplays
      - weechat
      - wf-recorder
      - whois
      - wofi
      - wordnet
      - wordnet-sense-index
      - youtube-dl
      - yubioath-desktop

- name: Launch KeepassXC via .desktop with 1.5x scale
  lineinfile:
    path: /usr/share/applications/org.keepassxc.KeePassXC.desktop
    regexp: '^Exec=keepassx.*'
    line: Exec=env QT_SCALE_FACTOR=1.5 keepassxc %f
