---

# Setup utils
- name: Install utilities
  apt:
    pkg:
      - archivemount
      - aria2
      - atool
      - bc
      - catdoc
      - checksec
      - colortest-python
      - command-not-found
      - docx2txt
      - entr
      - fzf
      - gcolor3
      - gnupg2
      - hexyl
      - jq
      - keepassxc
      - libsixel-bin
      - light
      - ncal
      - nmap
      - odt2txt
      - p7zip-full
      - pandoc
      - pmount
      - rar
      - rlwrap # cht.sh dependency
      - scdaemon
      - socat
      - taskwarrior
      - undertime
      - unicode-data
      - unrar
      - wget
      - whois
      - wordnet
      - wordnet-sense-index
      - yubioath-desktop
  when: setup_utils

- name: Install Wayland desktop
  apt:
    pkg:
      - adwaita-icon-theme
      - adwaita-qt
      - gnome-icon-theme
      - gnome-themes-standard
      - libglib2.0-bin # gsettings
      - mako-notifier
      - qtwayland5
      - slurp # screen area selector
      - sway
      - swaybg
      - swayidle
      - swaylock
      - waybar
      - wdisplays
      - wf-recorder
      - wl-clipboard
      - wofi
  when: setup_wayland

- name: Install Clevis
  apt:
    pkg:
      - clevis
      - clevis-initramfs
      - clevis-luks
      - clevis-tpm2
      - clevis-systemd
  when: setup_clevis

- name: Install fonts
  apt:
    pkg:
      - fonts-jetbrains-mono
      - fonts-ibm-plex
      - fonts-liberation
      - fonts-powerline
      - fonts-recommended
      - fonts-terminus
      - fonts-terminus-otb
  when: setup_fonts

- name: Install fuse/filesystems support
  apt:
    pkg:
      - dosfstools
      - exfatprogs
      - fuse-zip
      - gocryptfs
      - fuseiso
  when: setup_fs

- name: Install development tools
  apt:
    pkg:
      - bpython
      - cargo
      - git
      - libxml2-utils # xmllint
      - make
      - pax-utils
      - python3-pip
      - python3-virtualenv
      - rustc
      - strace
  when: setup_dev

- name: Install office tools
  apt:
    pkg:
      - dbus-x11 # needed by loffice apparently
      - dictionaries-common
      - hunspell
      - hunspell-en-au
      - liblibreofficekitgtk # needed for menus
      - libreoffice-gtk3
      - libreoffice-l10n-en-gb
      - libreoffice-style-sifr
      - lyx
      - mythes-en-au
  when: setup_office

- name: Install internet tools
  apt:
    pkg:
      - filezilla
      - firefox-esr
      - firefox-esr-l10n-en-gb
      - syncthing
      - syncthing-gtk
      - weechat
      - youtube-dl
  when: setup_internet

  # Setup multimedia
- block:
  - name: Install multimedia packages
    apt:
      pkg:
        - ffmpeg
        - imv
        - libimage-exiftool-perl
        - mpd
        - mpv
        - ncmpcpp
    when: setup_multimedia

  - name: Create mpd lyrics folder
    file:
      path: "{{ ansible_env.HOME }}/.cache/mpd/lyrics/"
      state: directory
      recurse: yes
    become: no
    tags:
      - wtf

  when: setup_multimedia
  # Block end
