---
- hosts: localhost
  tasks:


  - name: Execute `base` role
    include_role:
      name: base
      apply:
        tags:
          # Limit play via `ansible-playbook --tags role_*`
          - role_base
    tags:
      # `always` is a keyword here, not a tag.
      - always
    vars:
      # Refer to the respective READMEs for variables' descriptions and default values
      allow_reboot: false
      allow_ssh: false
      debs: []
      disable_bluetooth: true
      disable_firewire: true
      disable_hfs_udf: true
      disable_sleep_hibernate: false
      disable_speaker: false
      disable_thunderbolt: true
      fb_font_size: 10x18
      fstab_noexec: true
      generate_moduli: false
      grub_optional: ""
      grub_timeout: 1
      hide_pid: false
      locale: en_AU.UTF-8
      pkg_install_extra: true
      pkg_remove_defaults: true
      resolver_blocklist: ""
      resolver_install: true
      resolver_listen_on_ip: 127.0.0.1
      resolver_primary_hostname: dns.quad9.net
      resolver_primary_ip: 9.9.9.9
      resolver_secondary_hostname: dns.quad9.net
      resolver_secondary_ip: 149.112.112.112
      resolver_tls: true
      set_capslock: true
      set_dpkg_console: true
      set_dpkg_overrides: true
      set_hostname: false
      set_sigenforce: true
      sshd_less_secure: false
      sshguard_install: false
      sshguard_path: /etc/sshguard/sshguard.conf
      sudo_cmd_nopwd: "/usr/bin/alsaucm,/usr/bin/apt,/usr/bin/dmesg,/usr/bin/light"
      sudo_set: true
      sudo_user: tux
      timezone: Australia/Adelaide
      ufw_rule:
        - { comment: 'Drop incoming TCP traffic from 172.16.17.92 to port 22', direction: 'in', from: '172.16.17.92', port: '22', proto: 'tcp', rule: 'deny' }
        - { comment: 'Allow all traffic from 192.168.122.*', direction: 'in', from: '192.168.122.0/16', port: '1:65000', proto: 'tcp', rule: 'allow' }
      ufw_service:
        - { comment: 'Reject Yahoo messenger from 192.168.67.83', rule: 'deny', from: '192.168.67.83', service: 'Yahoo' }


  - name: Execute `laptop` role
    include_role:
      name: laptop
      apply:
        tags:
          - role_laptop
    tags:
      - always
    vars:
      alsa_out_card: 3
      alsa_out_device: 0
      alsa_setup: false
      disable_nmi_watch: true
      enable_sleep_suspend: true
      i2c_load_dev: true
      i2c_user_add: true
      intel_hda_options: ["model=thinkpad", "power_save_controller=Y"]
      logind_configure: false
      logind_idle_action: suspend
      logind_idle_time: 600
      logind_lid_action: suspend
      logind_powerbutton_action: poweroff
      set_trackpoint_drift: 25
      vm_writeback: 1500


  - name: Execute `software` role
    include_role:
      name: software
      apply:
        tags:
          - role_software
    tags:
      - always
    vars:
      setup_clevis: true
      setup_dev: true
      setup_fonts: true
      setup_fs: true
      setup_internet: true
      setup_multimedia: true
      setup_office: true
      setup_utils: true
      setup_wayland: true
      systemd_units_disable: ['tor@default.service', 'tor.service', 'mpd.service']
      systemd_units_enable: ['syncthing@myusername.service']
      systemd_units_masked: ['systemd-backlight@backlight:acpi_video0.service', 'mpd.service']
      virtio_install: true
      virtio_network_autostart: true
      virtio_use_default_network: true
      virtio_user_addgroup: true


  - name: Execute `dotfiles` role
    include_role:
      name: dotfiles
      apply:
        tags:
          - role_dotfiles
    tags:
      - always
    vars:
      change_tmux_prefix: false
      copy_dotfiles: false
      link_to_localhost: true
      remote_bash_emacs: false
      remote_gitconfig: false
      setup_neovim: true


  - name: Execute `transfer_agent` role
    include_role:
      name: transfer_agent
      apply:
        tags:
          - role_transfer
    tags:
      - never # prevents this from running unless requested via --tags never
    vars:
      add_rsync: true
      agent_group: agents
      agent_name: xfer_agent
      pubkey_from_current_user: true
      pubkey_from_others: true
      remove_existing_user: true


  - name: Execute `wireguard` role
    include_role:
      name: wireguard
      apply:
        tags:
          - role_wireguard
    tags:
      - never
    vars:
      wg_endpoints:
        - { name: 'Foo', pubkey: 'sPHxX6IiLpcJpgDmoXRuAiuZdKNJsZtsIEDJGK6ubmU=', psk: 'g1p3GiazEwyEoM2RkYh148/bu0w4zXg6S1I8ybw3fT0=', ip: '10.2.0.1', port: '12335', keepalive: '0', allowedips: '10.2.0.0/16' }
        - { name: 'Bar', pubkey: 'sPHxX6IiLpcJpgDmoXRuAiuZdKNJsZtsIEDJGK6ubmU=', psk: 'g1p3GiazEwyEoM2RkYh148/bu0w4zXg6S1I8ybw3fT0=', ip: '10.3.0.1', port: '22345', keepalive: '45', allowedips: '10.3.0.0/16' }
      wg_clients:
        - { name: 'Flob', pubkey: 'WC5a0cSWATZwLsQH1REjGcQsomZyEtRTaAqyRK20emY=', psk: 'yKsg+u7zY9N5rjgR3YE6cSu90aFBpxEPA3uKzK9vJc0=', ip: '10.2.1.10', keepalive: '0' }
        - { name: 'Fred', pubkey: 'qOwMjZuaVjfmdCSoOQbTp8MPADN+yB5gjRAmddA7jUM=', psk: 'Fo1UMMLxbyPiYwrJ/vE7tqPa66gblskjIc5xyQPsXgg=', ip: '10.3.1.20', keepalive: '90' }
      wg_autostart: true
      wg_forward: true
      wg_iface: wg8
      wg_overwrite: true
      wg_peerkey: OIxcoXM0NaNtsSZM7aNGDeqpUiQxkZ4+eG9OmLSFe3k=
      wg_port: 12345
      wg_server_ip: 10.0.0.10
      wg_server_subnet: '10.0.0.0/8'
      wg_ssh: true
      wg_start: true
      wg_systemd: true


  - name: Execute `EteSync` role
    include_role:
      name: etesync
      apply:
        tags:
          - role_etesync
    tags:
      - never
    vars:
      esc_admin: ''
      esc_admin_email: 'admin@example.com'
      esc_cert_email: 'certs@example.com'
      esc_debug: False
      esc_do_https: True
      esc_hosts: ['etesync.example.com']
      esc_path: '/var/www/esc_server'
      esc_port: 80
      esc_rm_existing: True
      esc_rootdir: '/var/www/html/esc_server'
      esc_user: 'www-uvicorn'
      esc_version: '43d5af32d72d5f59de7f31698076becf2430ccaa'
