---
- name: Hush login message
  file:
    path: "{{ ansible_env.HOME }}/.hushlogin"
    state: touch
    modification_time: preserve
    access_time: preserve

- name: Create dotfiles folder
  file:
    path: "{{ ansible_env.HOME }}/.local/etc/dotfiles"
    state: directory
  when: copy_dotfiles == true

- name: Copy primary dotfiles to the remote machine
  copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/.local/etc/dotfiles/{{ item.src }}"
  with_items: "{{ dotfiles_list }}"
  when: copy_dotfiles == true

- name: Check if tmux terminfo already installed
  shell: infocmp -x tmux
  register: terminfo_test
  changed_when: False

- name: Copy tmux terminfo
  copy:
    src: tmux_terminfo
    dest: "{{ ansible_env.HOME }}/.tmux_terminfo"
  when: terminfo_test.rc | int != 0
  
- name: Install tmux terminfo
  shell: tic -x "{{ ansible_env.HOME }}/.tmux_terminfo"
  register: terminfo_installed
  when: terminfo_test.rc | int != 0

- name: Delete terminfo file
  file:
    path: "{{ ansible_env.HOME }}/.tmux_terminfo"
    state: absent
  when: terminfo_installed.changed and not terminfo_installed.failed
