---
- name: Hush login message
  file:
    path: "{{ ansible_env.HOME }}/.hushlogin"
    state: touch

- name: Copy primary dotfiles to the remote machine
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.{{ item }}"
  with_items:
    - bash_profile
    - aliases
    - bashrc
    - curlrc
    - gitconfig
    - gitignore
    - inputrc
    - profile
    - tmux_terminfo
    - tmux.conf
  when: ansible_connection != "local"

- name: Copy SSH client config
  copy:
    src: ssh_config
    dest: "{{ ansible_env.HOME }}/.ssh/config"

- name: Check if tmux terminfo already installed
  shell: infocmp -x tmux
  register: terminfo_test

- name: Install tmux terminfo
  shell: tic -x "{{ ansible_env.HOME }}/.tmux_terminfo"
  register: terminfo_installed
  when: terminfo_test['stdout'].splitlines()[0] is search("Reconstructed")

- name: Delete terminfo file
  file:
    path: "{{ ansible_env.HOME }}/.tmux_terminfo"
    state: absent
  when: terminfo_installed

- name: Don't use the same prefix in remote tmux
  # This is normally done via `template`, but due to the small changes required
  # in the whole config, I have decided to handle it with `lineinfile` module
  lineinfile:
    path: ~/.tmux.conf
    line: "# -- Replaced by Ansible --"
    regexp: "{{ item }}"
  with_items:
    - "^unbind\ C-b"
    - "^set\ -g\ prefix"
    - "^bind\ C-Space"
    - "^set-option\ -s\ set-clipboard\ on"
    - "^bind-key\ -T\ copy-mode-vi"
    - "^bind-key\ -Tcopy-mode-vi"
    - "^bind\ p\ paste-buffer"
  when: ansible_connection != "local"

- name: Don't use vi mode in remote bash
  lineinfile:
    path: ~/.bashrc
    line: "set -o emacs"
    regexp: "set\ -o\ vi"
  when: remote_bash_emacs == true
