---
- name: Link dotfiles to the home folder
  file: src={{role_path}}/files/{{ item.src }}  dest={{ ansible_env.HOME }}/{{ item.dest }} state=link force=yes
  with_items:
    - { src: 'aliases', dest: '.aliases' }
    - { src: 'bash_profile', dest: '.bash_profile' }
    - { src: 'bashrc', dest: '.bashrc' }
    - { src: 'curlrc', dest: '.curlrc' }
    - { src: 'gitconfig', dest: '.gitconfig' }
    - { src: 'gitignore', dest: '.gitignore' }
    - { src: 'gpg.conf', dest: '.gnupg/gpg.conf' }
    - { src: 'i3', dest: '.i3' }
    - { src: 'inputrc', dest: '.inputrc' }
    - { src: 'muttrc', dest: '.muttrc' }
    - { src: 'profile', dest: '.profile' }
    - { src: 'tmux.conf', dest: '.tmux.conf' }
    - { src: 'weechat.conf', dest: 'weechat.conf' }
    - { src: 'vimrc', dest: '.vimrc' }
    - { src: 'Xresources', dest: '.Xresources' }
    - { src: 'ssh_config', dest: '.ssh/config' }
  when: ansible_connection == "local" and not WSL1
