---
- name: Add tmux.conf to the list of dotfiles, no prefix change
  set_fact:
    dotfiles_list: "{{ dotfiles_list | union(dotfiles_list_tmux) }}"
  when: not change_prefix

  #
  # `copy_dotfiles`
  #
- block:

  - name: Create dotfiles folder
    file:
      path: "{{ ansible_env.HOME }}/.local/etc/dotfiles"
      state: directory

  - name: Copy primary dotfiles to the remote machine
    copy:
      src: "{{ item.src }}"
      dest: "{{ ansible_env.HOME }}/.local/etc/dotfiles/{{ item.src }}"
    with_items: "{{ dotfiles_list }}"

  - name: Link dotfiles from ~/.local/etc/dotfiles to $HOME
    become: yes
    become_user: "{{ ansible_env.USER }}"
    file:
      src: "{{ ansible_env.HOME }}/.local/etc/dotfiles/{{ item.src }}"
      dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
      state: link
      force: yes
    with_items: "{{ dotfiles_list }}"
    register: dotfiles_linked

  when: copy_dotfiles

  #
  # Link from this role
  #
- name: Link dotfiles from this role to $HOME
  file:
    src: "{{role_path}}/files/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.dest }}"
    state: link
    force: yes
  with_items: "{{ dotfiles_list }}"
  when: link_to_localhost and not WSL1 and not copy_dotfiles
  register: dotfiles_linked
