---
- name: Don't use vi mode in remote bash
  lineinfile:
    path: ~/.bashrc
    line: "set -o emacs"
    regexp: "set\ -o\ vi"
  when: remote_bash_emacs == true

  block:
    - name: Lookup tmux.conf into a var
      set_fact:
        tmux_conf_orig: "{{ lookup('file', 'tmux.conf').split('\n') | list }}"

    - name: Remove config options unsuitable for a remote tmux
      set_fact:
        tmux_conf_changed: "{{ tmux_conf_orig | difference(tmux_remove_lines) }}"

    - name: Write tmux config to a file
      copy:
        dest: "{{ ansible_env.HOME }}/.local/etc/dotfiles/tmux.conf }}"
        content: "{{ tmux_conf_changed | join( '\n' ) }}"
  when: copy_dotfiles == true
