---
- name: Don't use the same prefix in remote tmux
  # This is normally done via `template`, but due to the small changes required
  # in the whole config, I have decided to handle it with `lineinfile` module
  lineinfile:
    path: ~/.tmux.conf
    line: "# -- Don't use the same prefix in remote tmux"
    regexp: "{{ item }}"
  with_items:
    - "^unbind\ C-b"
    - "^set\ -g\ prefix"
    - "^bind\ C-Space"
    - "^set-option\ -s\ set-clipboard\ on"
    - "^bind-key\ -T\ copy-mode-vi"
    - "^bind-key\ -Tcopy-mode-vi"
    - "^bind\ p\ paste-buffer"
  when: ansible_connection != "local" and change_prefix == True

- name: Don't use vi mode in remote bash
  lineinfile:
    path: ~/.bashrc
    line: "set -o emacs"
    regexp: "set\ -o\ vi"
  when: remote_bash_emacs == true
