---
- name: Create nVim init folder
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory
    mode: 0755

- name: Create auxiliary vim folders
  file:
    path: "{{ ansible_env.HOME }}/.vim/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - backup
    - tmp
    - undo

- name: Create NeoVim init file
  copy:
    content: "set runtimepath^=~/.vim runtimepath+=~/.vim/after\n
              let &packpath = &runtimepath\n
              source ~/.vimrc\n"
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"

- name: Copy colour-schemes
  copy:
    src: vim/colors
    dest: "{{ ansible_env.HOME }}/.vim"

- name: Create site-packages root
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack"
    state: directory

- name: Create package folders
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/{{ item }}/start"
    state: directory
  with_items: "{{ neovim_plugins }}"

- name: Copy plugins
  copy:
    src: "vim/{{ item }}"
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/{{ item }}/start"
  with_items: "{{ neovim_plugins }}"

- name: Make `preview.sh` executable
  file:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/fzf.vim/start/fzf.vim/bin/preview.sh"
    mode: a+x
