---
- name: Create nVim init folder
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory
    mode: 0755

- name: Create auxiliary vim folders
  file:
    path: "{{ ansible_env.HOME }}/.vim/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - backup
    - tmp
    - undo

- name: Create NeoVim init file
  copy:
    content: "set runtimepath^=~/.vim runtimepath+=~/.vim/after\n
              let &packpath = &runtimepath\n
              source ~/.vimrc\n"
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"

- name: Copy .vimrc
  copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"