---
- name: Create nVim init folder
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory
    mode: 0755

- name: Create auxiliary vim folders
  file:
    path: "{{ ansible_env.HOME }}/.vim/{{ item }}"
    state: directory
    mode: 755
  with_items:
    - backup
    - tmp
    - undo

- name: Create NeoVim init file
  copy:
    content: "set runtimepath^=~/.vim runtimepath+=~/.vim/after\n
              let &packpath = &runtimepath\n
              source ~/.vimrc\n"
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"

- name: Copy .vimrc
  copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"

- name: Install NVim plug
  shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  when: neovim

- name: Update NVim gem
  command: gem update neovim

- name: Update neovim pip module
  pip:
    name: neovim
    executable: pip

- name: Update neovim pip3 module
  pip:
    name: neovim
    executable: pip3

- name: Install nVIM plugins and exit
  shell: nvim +PlugUpdate +sleep1000m +exit +sleep1000m +exit
  async: 45
  poll: 5
