---
- name: Copy source dotfiles to the target host
  import_tasks: dotfiles_propagate.yml
  tags:
    - dotfiles_propagate

- name: Setup NeoVim
  import_tasks: dotfiles_neovim.yml
  when: neovim == true
  tags:
    - dotfiles_neovim

- name: Link dotfiles to $HOME
  import_tasks: dotfiles_link.yml
  tags:
    - dotfiles_link

- name: Adapt dotfiles for a remote host
  import_tasks: dotfiles_remote.yml
  tags:
    - dotfiles_remote
