---
- name: restart sshd
  service:
    name: sshd
    state: restarted
  become: yes
  listen: "restart sshd"

- name: restart ufw
  service:
    name: ufw
    state: restarted
  become: yes
  listen: "restart ufw"

- name: restart rsyncd
  service:
    name: rsync
    state: restarted
  become: yes
  listen: "restart rsyncd"

- name: reload sysctl
  shell: sysctl --system
  become: yes
  listen: "reload sysctl"

- name: restart timesyncd
  service:
    name: systemd-timesyncd
    state: restarted
  become: yes
  listen: "restart timesyncd"

- name: reconfigure keyboard settings
  shell: dpkg-reconfigure -f noninteractive keyboard-configuration
  become: yes
  listen: "dpkg_keyboard"

- name: restart sshguard
  service:
    name: sshguard
    state: restarted
  become: yes
  listen: "restart sshguard"

- name: Restart Knot
  service:
    name: kresd@1
    state: restarted
  become: yes
  listen: "restart kresd"

- name: Update GRUB
  command: grub-mkconfig -o /boot/grub/grub.cfg && update-grub
  listen: "grub_update"
  become: yes
  notify: reboot host

- name: Rotate logs
  command: "logrotate -f /etc/logrotate.conf"
  become: yes
  listen: "rotate logs"

- name: Reload systemd
  systemd:
    daemon_reexec: yes
    daemon_reload: yes
    state: restarted
    name: local-fs.target
  become: yes
  listen: "reload systemd"

- name: Reboot target host
  reboot:
    msg: "Rebooting {{ ansible_hostname | upper }} @ {{ ansible_host }}"
    connect_timeout: 5
    reboot_timeout: 600
    post_reboot_delay: 10
  become: yes
  when: ansible_connection != "local" and allow_reboot == true
  listen: "reboot host"
