---
- name: restart sshd
  service: name=sshd state=restarted
  listen: "restart sshd"

- name: restart ufw
  service: name=ufw state=restarted
  listen: "restart ufw"

- name: reload sysctl
  shell: sysctl --system
  listen: "reload sysctl"

- name: restart timesyncd
  service: name=systemd-timesyncd state=restarted
  listen: "restart timesyncd"

- name: reboot
  shell: sleep 2 && shutdown -r now 'Ansible maintenance reboot'
  async: 1
  poll: 0
  ignore_errors: true
  listen: "reboot computer"

- name: reconfigure keyboard settings
  shell: dpkg-reconfigure -f noninteractive keyboard-configuration
  become: yes
  listen: "dpkg_keyboard"

- name: Update GRUB
  command: grub-mkconfig -o /boot/grub/grub.cfg && update-grub
  listen: "grub_update"

- name: restart sshguard
  service: name=sshguard state=restarted
  listen: "restart sshguard"
