---
kernel_version: "{{ ansible_facts['kernel'] }}"
WSL1: "{{ kernel_version is regex('.*Microsoft$') }}"
dotfiles_list:
  - { src: 'aliases', dest: '.aliases' }
  - { src: 'bash_profile', dest: '.bash_profile' }
  - { src: 'bashrc', dest: '.bashrc' }
  - { src: 'curlrc', dest: '.curlrc' }
  - { src: 'gitconfig', dest: '.gitconfig' }
  - { src: 'gitignore', dest: '.gitignore' }
  - { src: 'gpg.conf', dest: '.gnupg/gpg.conf' }
  - { src: 'i3', dest: '.i3' }
  - { src: 'inputrc', dest: '.inputrc' }
  - { src: 'muttrc', dest: '.muttrc' }
  - { src: 'profile', dest: '.profile' }
  - { src: 'tmux.conf', dest: '.tmux.conf' }
  - { src: 'weechat.conf', dest: 'weechat.conf' }
  - { src: 'vimrc', dest: '.vimrc' }
  - { src: 'Xresources', dest: '.Xresources' }
  - { src: 'ssh_config', dest: '.ssh/config' }
