---
- name: Run sanity-checks
  import_tasks: assertions.yml
  become: yes
  tags:
    - laptop_assert

- name: Install laptop packages
  import_tasks: packages_laptop.yml
  become: yes
  tags:
    - laptop_packages

- name: Notebook-specific settings
  import_tasks: notebook.yml
  become: yes
  tags:
    - laptop_notebook

- name: Setup ALSA
  import_tasks: alsa.yml
  when: alsa_setup
  become: no
  tags:
    - laptop_alsa

- name: Run all relevant handlers
  meta: flush_handlers
