---
- name: Add user to i2c group
  user:
    append: yes
    groups: i2c
    name: "{{ ansible_env.USER }}"
  when: user_add_i2c

- name: Unmask sleep, suspend and hibernate systemd targets
  systemd:
    name: "{{ item }}"
    masked: no
  with_items:
    - "sleep.target"
    - "suspend.target"
    - "hibernate.target"
    - "hybrid-sleep.target"
  when: enable_sleep_hibernate

- name: Configure suspend and hibernate in logind.conf
  lineinfile:
    path: /etc/systemd/logind.conf
    line: "{{ item }}"
  with_items:
    - 'IdleAction="{{ logind_idle_action }}"'
    - 'IdleActionSec="{{ logind_idle_time }}"'
    - 'HandleLidSwitch="{{ logind_lid_action }}"'
    - 'HandlePowerKey={{ logind_powerbutton_action }}"'

- name: Configure suspend and hibernate in sleep.conf
  lineinfile:
    path: /etc/systemd/sleep.conf
    line: "{{ item }}"
  with_items:
    - 'HibernateDelaySec="{{ logind_hibernate_delay }}"'

- name: Create laptop sysctl override
  file:
    path: /etc/sysctl.d/laptop.conf
    state: file
    mode: 0644
    owner: root
  become: true

- name: Set VM writeback timeout
  lineinfile:
    path: /etc/sysctl.d/laptop.conf
    line: "vm.dirty_writeback_centisecs={{ vm_writeback }}"
  become: true

- name: Disable NMI watchdog
  lineinfile:
    path: /etc/sysctl.d/laptop.conf
    line: "kernel.nmi_watchdog=0"
  become: true
  when: disable_nmi_watch
