---
- name: Add user to i2c group
  user:
    append: yes
    groups: i2c
    name: '{{ ansible_env.USER }}'
  when: i2c_user_add

- name: Load `i2c-dev` module on boot
  copy:
    content: 'i2c-dev'
    dest: /etc/modules-load.d/i2c-dev.conf
  become: true
  when: i2c_load_dev

  # sleep - turn off screens
  # suspend - enter S3
- name: Unmask sleep and suspend systemd targets
  systemd:
    name: '{{ item }}'
    masked: no
  with_items:
    - "sleep.target"
    - "suspend.target"
  when: enable_sleep_suspend

- name: Configure sleep and suspend in logind.conf
  lineinfile:
    path: /etc/systemd/logind.conf
    line: '{{ item.key }}={{ item.value }}'
    regexp: '.*"{{ item.key }}"\=.*'
  with_items:
    - { key: 'IdleAction', value: '{{ logind_idle_action }}' }
    - { key: 'IdleActionSec', value: '{{ logind_idle_time }}' }
    - { key: 'HandleLidSwitch', value: '{{ logind_lid_action }}' }
    - { key: 'HandlePowerKey', value: '{{ logind_powerbutton_action }}' }
  when: logind_configure

- name: Set VM writeback timeout
  lineinfile:
    path: /etc/sysctl.d/laptop.conf
    line: 'vm.dirty_writeback_centisecs={{ vm_writeback }}'
    create: true
  become: true

- name: Disable NMI watchdog
  lineinfile:
    path: /etc/sysctl.d/laptop.conf
    line: 'kernel.nmi_watchdog=0'
  become: true
  when: disable_nmi_watch
