---
- name: Download information about latest versions
  apt:
    update-cache: yes
    cache_valid_time: 3600

- name: Upgrade packages
  apt:
    upgrade: 'yes' # https://serverfault.com/a/993211

- name: Remove unneeded packages
  apt:
    autoremove: true
