---
- name: Download information about latest versions
  apt:
    update-cache: True
    cache_valid_time: 3600

- name: Upgrade packages
  apt:
    upgrade: 'yes' # https://serverfault.com/a/993211

- name: Run `apt autoremove`
  apt:
    autoremove: true
