---
- name: Register hash of /etc/ssh/moduli
  stat:
    path: "/etc/ssh/moduli"
  register: st_moduli

- name: Set fact about our findings
  set_fact:
    generate_moduli: yes
  when: (st_moduli.stat['checksum'] == "6541fc14923473fcd2e04c98248c9ef2613050b1" or st_moduli.stat['checksum'] == "a4b506a8095b6598a1dad573fd492bbb047b31ad")

- name: Generate primes pool
  shell: ssh-keygen -G "{{ansible_env.HOME}}/moduli.in" -b 4096
  when: generate_moduli is defined
  register: primes_pool_is_ready

- name: Select primes
  shell: ssh-keygen -T "{{ansible_env.HOME}}/moduli.out" -f "{{ansible_env.HOME}}/moduli.in"
  when: primes_pool_is_ready.changed
  register: primes_are_ok

- name: Copy output
  copy:
    src: "{{ansible_env.HOME}}/moduli.out"
    dest: /etc/ssh/moduli
    remote_src: true
    backup: yes
  when: primes_are_ok.changed
  register: primes_are_copied
  notify: restart sshd

- name: Remove tmp files
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "{{ansible_env.HOME}}/moduli.in"
    - "{{ansible_env.HOME}}/moduli.out"
  when: primes_are_copied.changed
