---
- name: Install list of packages
  apt:
    name: "{{ pkg }}"
  vars:
    pkg:
      - apt-listchanges
      - apt-transport-https
      - bash-completion
      - ca-certificates
      - curl
      - debian-goodies
      - debsecan
      - debsums
      - dfc
      - dnsutils
      - git
      - gnupg
      - gnupg2
      - grc
      - htop
      - ioping
      - knot-resolver
      - knot-resolver-module-http
      - libpam-tmpdir
      - lshw
      - lsof
      - man-db
      - mc
      - ncdu
      - needrestart
      - neovim
      - neovim-runtime
      - python
      - python-pip
      - python3
      - python3-pip
      - rsync
      - ruby
      - ruby-dev
      - silversearcher-ag
      - sshguard
      - strace
      - sudo
      - sysstat
      - tmux
      - tree
      - unattended-upgrades
      - wget

- name: Ensure ~/.gnupg is initialized
  shell: gpg2 -k
