---
- name: Check if there is NetworkManager conf.d
  stat:
    path: /etc/NetworkManager/conf.d
  register: check_network_manager

- name: Ensure NetworkManager won't override resolv.conf
  copy:
    dest: /etc/NetworkManager/conf.d/no-dns.conf
    content: "[main]\ndns=none\n"
  when: check_network_manager.stat.exists and check_network_manager.stat.isdir

- name: Copy Knot settings
  copy:
    src: kresd.conf
    dest: /etc/knot-resolver/kresd.conf
    owner: root
    mode: 0644

- name: Enable Knot resolver
  shell: systemctl enable --now kresd@1.service

- name: Restart Knot-resolver
  systemd:
    state: restarted
    daemon_reload: yes
    name: kresd@1

- name: Switch to the local resolver
  copy:
    dest: /etc/resolv.conf
    content: '127.0.0.1'

- name: Make /etc/resolv.conf immutable
  file:
    path: /etc/resolv.conf
    attr: +i

- name: Create /etc/hosts_blocked
  file:
    path: /etc/hosts_blocked
    state: touch
    owner: root
    mode: 0644
