---
- name: Create NetworkManager config folder
  file:
    path: /etc/NetworkManager/conf.d/
    state: directory
    recurse: yes

- name: Ensure NetworkManager won't override resolv.conf
  copy:
    dest: /etc/NetworkManager/conf.d/no-dns.conf
    content: "[main]\ndns=none\n"

- name: Ensure `resolvconf` package won't override resolv.conf
  copy:
    dest: /etc/resolvconf.conf
    content: "resolvconf=NO"

- name: Copy Knot settings
  copy:
    src: kresd.conf
    dest: /etc/knot-resolver/kresd.conf
    owner: root
    mode: 0644

- name: Switch to the local resolver
  copy:
    dest: /etc/resolv.conf
    content: '127.0.0.1'

- name: Make /etc/resolv.conf immutable
  file:
    path: /etc/resolv.conf
    attr: ie

- name: Create /etc/hosts_blocked
  file:
    path: /etc/hosts_blocked
    state: file
    owner: root
    mode: 0644

- name: Enable Knot resolver
  service:
    name: kresd@1
    enabled: yes

