---
- name: Purge contradictory packages
  apt:
    state: absent
    purge: True
    autoremove: True
    name:
    - wpasupplicant
    - rpcbind
    - exim4
    - bind9
    - avahi-daemon
    - dnsmasq
    - ntp
