---
- name: Install basic list of packages
  apt:
    name: '{{ pkg }}'
  vars:
    pkg:
      - apparmor
      - apparmor-utils
      - bash-completion
      - bind9-dnsutils
      - ca-certificates
      - gnupg2
      - libpam-tmpdir
      - man-db
      - needrestart
      - net-tools
      - rng-tools5
      - unattended-upgrades

- name: Install Intel CPU firmware if necessary
  apt:
    name: intel-microcode
  when: '"Intel" in cpu_vendor and not WSL2'

- name: Install AMD CPU firmware if necessary
  apt:
    name: amd64-microcode
  when: '"AMD" in cpu_vendor and not WSL2'

- name: Check pubring and trust-db in ~/.gnupg/
  stat:
    path: '{{ ansible_env.HOME }}/.gnupg/{{ item }}'
  with_items:
    - "pubring.kbx"
    - "trustdb.gpg"
  register: gpg_stat

- name: Set intermediate fact about our findings...
  no_log: true
  set_fact:
    gpg_files_found: '{{ gpg_files_found + [item.stat.exists] }}'
  with_items:
    - '{{ gpg_stat.results }}'

- name: Create single 'GPG-result' variable...
  set_fact:
    gpg_db_initialised: '{{ gpg_files_found | unique | join() | bool }}'

- name: Initialise ~/.gnupg
  shell: gpg -k
  when: not gpg_db_initialised

- name: Configure unattended-upgrades
  copy:
    src: conf/unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
