---
- name: Copy /etc/ssh/sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    mode: 0644
  notify:
    - restart sshd

- name: Enable less secure ciphers
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^Ciphers\s'
    line: "Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-cbc"
  when: sshd_less_secure == True

- name: Enable less secure MACs
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^MACs\s'
    line: "hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha-256"
  when: sshd_less_secure == True

- name: Copy /etc/sysctl.conf
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    mode: 0644
  notify:
    - reload sysctl

- name: Blacklist SPECK module
  copy:
    content: "blacklist CONFIG_CRYPTO_SPECK"
    dest: /etc/modprobe.d/blacklist.conf
  become: yes
  when: ansible_distribution == 'Debian'

- name: Modify /etc/issue
  copy:
    dest: "{{ item }}"
    content: 'Access to this computer is prohibited.'
  with_items:
    - /etc/issue
    - /etc/issue.net

- name: Change CapsLock to Ctrl
  replace:
    path: /etc/default/keyboard
    regexp: '^XKBOPTIONS'
    replace: 'XKBOPTIONS="caps:ctrl_modifier"'
  notify:
    - dpkg_keyboard

- name: GRUB settings
  lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet apparmor=1 loglevel=5 security=apparmor ipv6.disable=1 slab_nomerge slub_debug=FZP mce=0 page_poison=1 mitigations=auto audit=0 intel_iommu=on amd_iommu=on efi=disable_early_pci_dma init_on_alloc=1 init_on_free=1 pti=on vsyscall=none page_alloc.shuffle=1 extra_latent_entropy"'
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
  notify: grub_update

- name: Disable acces to /proc in /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "proc /proc proc nosuid,nodev,noexec,hidepid=1 0 0"
    insertafter: EOF
    state: present

- name: Ensure systemd-logind.service.d exists
  file:
    path: /etc/systemd/system/systemd-logind.service.d
    recurse: yes
    state: directory

- name: Update systemd with supplementary "proc" group
  copy:
    dest: /etc/systemd/system/systemd-logind.service.d/hidepid.conf
    content: "[Service]\nSupplementaryGroups=proc"

- name: Ensure /etc/systemd/coredump.conf.d exists
  file:
    path: /etc/systemd/coredump.conf.d
    recurse: yes
    state: directory

- name: Instruct systemd to not store coredumps
  copy:
    dest: /etc/systemd/coredump.conf.d/custom.conf
    content: "[Coredump]\nStorage=none"

- name: Set zero limit to prevent dumps from being written to disk
  lineinfile:
    path: /etc/security/limits.conf
    line: "\n* hard core 0\n"
    insertbefore: '^#\ End\ of\ file'
    state: present

- name: Prevent applications with setuid from dumping their memory
  copy:
    dest: /etc/sysctl.d/suid_dumpable.conf
    content: "fs.suid_dumpable=0"

- name: Add 4s. delay to failed login attempts
  copy:
    dest: /etc/pam.d/system-login
    content: "auth optional pam_faildelay.so delay=4000000"

- name: Block unnecessary network protocols
  copy:
    src: uncommon-network-protocols.conf
    dest: /etc/modprobe.d/uncommon-network-protocols.conf

- name: Disable pc-speaker (don't beep)
  copy:
    dest: /etc/modprobe.d/blacklist_speaker.conf
    content: "blacklist pcspkr"

- name: Enable APT sandboxing
  copy:
    dest: /etc/apt/apt.conf.d/02sandboxing
    content: 'APT::Sandbox::Seccomp "true";'
