---
- name: Copy /etc/ssh/sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    mode: 0644
  notify:
    - restart sshd

- name: Copy /etc/sysctl.conf
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    mode: 0644
  notify:
    - reload sysctl

- name: Blacklist SPECK module
  copy:
    content: "blacklist CONFIG_CRYPTO_SPECK"
    dest: /etc/modprobe.d/blacklist.conf
  become: yes
  when: ansible_distribution == 'Debian'

- name: Modify /etc/issue
  copy:
    dest: "{{ item }}"
    content: 'Access to this computer is prohibited.'
  with_items:
    - /etc/issue

- name: Change CapsLock to Ctrl
  replace:
    path: /etc/default/keyboard
    regexp: '^XKBOPTIONS'
    replace: 'XKBOPTIONS="caps:ctrl_modifier"'
  notify:
    - dpkg_keyboard

- name: GRUB settings
  lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet apparmor=1 security=apparmor ipv6.disable=1 slab_nomerge slub_debug=FZP mce=0 page_poison=1 mitigations=auto audit=1"'
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
  notify: grub_update
