---
- name: Copy /etc/ssh/sshd_config
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    mode: 0644
  notify:
    - restart sshd

- name: Copy /etc/sysctl.conf
  copy:
    src: sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    mode: 0644
  notify:
    - reload sysctl

- name: Blacklist SPECK module
  copy:
    content: "blacklist CONFIG_CRYPTO_SPECK"
    dest: /etc/modprobe.d/blacklist.conf
  become: yes
  when: ansible_distribution == 'Debian'

- name: Modify /etc/issue
  copy:
    dest: "{{ item }}"
    content: 'Access to this computer is prohibited.'
  with_items:
    - /etc/issue

- name: Change CapsLock to Ctrl
  replace:
    path: /etc/default/keyboard
    regexp: '^XKBOPTIONS'
    replace: 'XKBOPTIONS="caps:ctrl_modifier"'
  notify:
    - dpkg_keyboard

- name: GRUB settings
  lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet apparmor=1 security=apparmor ipv6.disable=1 slab_nomerge slub_debug=FZP mce=0 page_poison=1 mitigations=auto audit=1"'
    regexp: "^GRUB_CMDLINE_LINUX_DEFAULT"
  notify: grub_update

- name: Disable acces to /proc in /etc/fstab
  lineinfile:
    path: /etc/fstab
    line: "proc /proc proc nosuid,nodev,noexec,hidepid=2,gid=proc 0 0"
    insertafter: EOF
    state: present

- name: Ensure systemd-logind.service.d exists
  file:
    path: /etc/systemd/system/systemd-logind.service.d
    recurse: yes
    state: directory

- name: Update systemd with supplementary "proc" group
  copy:
    dest: /etc/systemd/system/systemd-logind.service.d/hidepid.conf
    content: "[Service]\nSupplementaryGroups=proc"

- name: Ensure /etc/systemd/coredump.conf.d exists
  file:
    path: /etc/systemd/coredump.conf.d
    recurse: yes
    state: directory

- name: Instruct systemd to not store coredumps
  copy:
    dest: /etc/systemd/coredump.conf.d/custom.conf
    content: "[Coredump]\nStorage=none"

- name: Set zero limit to prevent dumps from being written to disk
  lineinfile:
    path: /etc/security/limits.conf
    line: "\n* hard core 0\n"
    insertbefore: '^#\ End\ of\ file'
    state: present

- name: Prevent applications with setuid from dumping their memory
  copy:
    dest: /etc/sysctl.d/suid_dumpable.conf
    content: "fs.suid_dumpable=0"

- name: Add 4s. delay to failed login attempts
  copy:
    dest: /etc/pam.d/system-login
    content: "auth optional pam_faildelay.so delay=4000000"

