---
- name: Adjust sudo defaults
  lineinfile:
    path: /etc/sudoers
    line: '{{ item }}'
    insertafter: '^Defaults.*'
  with_items:
    - "Defaults  requiretty"
    - "Defaults  use_pty"
    - 'Defaults  lecture="never"'
    - "Defaults  insults"

- name: Add target user to `sudo` group
  user:
    append: True
    groups: sudo
    name: '{{ sudo_user }}'
  when:
    - sudo_user != 'root'
    - sudo_set

- name: Allow target user to execute certain commands with `sudo` and without password
  lineinfile:
      path: /etc/sudoers
      state: present
      insertafter: '^%sudo  ALL=(ALL:ALL) ALL'
      line: '{{ sudo_user }} ALL=NOPASSWD:{{ sudo_cmd_nopwd }}'
      validate: '/usr/sbin/visudo -cf %s'
  become: True
  when:
    - sudo_cmd_nopwd | length > 6
    - sudo_user != 'root'
    - sudo_set
