---
- name: Set timezone
  timezone:
    name: '{{ timezone }}'

- name: Enable systemd-timesyncd service
  service:
    name: systemd-timesyncd
    enabled: true
    state: started
  when: not WSL1 and not WSL2

- name: Copy /etc/systemd/timesyncd.conf
  copy:
    src: conf/timesyncd.conf
    dest: /etc/systemd/timesyncd.conf
    mode: preserve
  when: not WSL1 and not WSL2
  notify:
    - restart timesyncd
