galaxy_info:
  author: Andrew Savchenko
  description: Basic setup of sensible Debian machine
  company: stoptracking.net

  issue_tracker_url: https://github.com/stoptracking/playbook/issues
  license: MIT
  min_ansible_version: 2.4

  platforms:
    - name: Debian
      versions:
        - stretch
        - buster

  galaxy_tags:
    - debian
    - linux
    - stoptracking

dependencies: []
