---
- name: Download latest hosts from the mirrors
  import_tasks: fetch_hosts.yml
  delegate_to: localhost
  run_once: yes

- name: Assemble hosts in the single file and clean-up afterwards
  import_tasks: assemble_hosts.yml
  delegate_to: localhost
  run_once: yes

- name: Copy new `hosts_blocked` to the /etc
  include_tasks: copy_hosts.yml
