---

# If you are running an instance of Syncthing on the discovery server, you
# must either add that instance to other devices using a static address or
# bind the discovery server and Syncthing instances to different IP
# addresses.

- name: 
